In [ ]:
# Import NumPy and verify that it is available

import numpy as np

print("NumPy Imported Successfully")

NumPy Imported Successfully


In [ ]:
# Create a NumPy array
import numpy as np

packages = np.array([120, 145, 132, 168, 151, 174, 160])

# Display the array and calculate basic statistics
print("Packages:", packages)
print("Total Packages:", np.sum(packages))
print("Average Packages:", np.mean(packages))
print("Highest Dispatch:", np.max(packages))
print("Lowest Dispatch:", np.min(packages))


Packages: [120 145 132 168 151 174 160]
Total Packages: 1050
Average Packages: 150.0
Highest Dispatch: 174
Lowest Dispatch: 120


In [ ]:
# Create a NumPy array
import numpy as np

passengers = np.array([210, 185, 240, 265, 220, 250])

# Calculate basic statistics
print("Hourly Passengers:", passengers)
print("Total Passengers:", np.sum(passengers))
print("Average Passengers:", np.mean(passengers))
print("Maximum Passengers:", np.max(passengers))
print("Minimum Passengers:", np.min(passengers))


Hourly Passengers: [210 185 240 265 220 250]
Total Passengers: 1370
Average Passengers: 228.33333333333334
Maximum Passengers: 265
Minimum Passengers: 185


In [ ]:
# Create arrays using NumPy array-generation functions
import numpy as np

print("Sensor IDs")
print(np.arange(101, 111))

print("\nMachine Status Matrix")
print(np.ones((3, 4)))

print("\nFault Matrix")
print(np.zeros((3, 4)))

print("\nDefault Temperature")
print(np.full((3, 4), 25))

print("\nMemory Allocation")
print(np.empty((2, 3)))

print("\nCalibration Levels")
print(np.linspace(0, 100, 6))

print("\nIdentity Matrix")
print(np.eye(4))


Sensor IDs
[101 102 103 104 105 106 107 108 109 110]

Machine Status Matrix
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Fault Matrix
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Default Temperature
[[25 25 25 25]
 [25 25 25 25]
 [25 25 25 25]]

Memory Allocation
[[0.00000000e+000 5.18413201e-317 2.96439388e-323]
 [            nan 5.18740668e-317 6.81164808e-310]]

Calibration Levels
[  0.  20.  40.  60.  80. 100.]

Identity Matrix
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Create and display NumPy matrices
import numpy as np

pixel_values = np.array([
    [120, 130, 140],
    [150, 160, 170],
    [180, 190, 200]
])

# Display the original matrix
print("Original Image Matrix")
print(pixel_values)

# Create a zero matrix
print("\nBlank Image")
print(np.zeros((3, 3)))

# Create a matrix filled with 255
print("\nWhite Image")
print(np.full((3, 3), 255))

# Create an identity matrix
print("\nIdentity Filter")
print(np.identity(3))


Original Image Matrix
[[120 130 140]
 [150 160 170]
 [180 190 200]]

Blank Image
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

White Image
[[255 255 255]
 [255 255 255]
 [255 255 255]]

Identity Filter
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Create a 2D NumPy array and inspect its attributes
import numpy as np

patients = np.array([
    [98.6, 72, 120],
    [99.1, 76, 118],
    [100.2, 80, 122],
    [98.4, 70, 115]
])

# Display array attributes
print("Patient Data")
print(patients)
print("\nDimensions :", patients.ndim)
print("Shape :", patients.shape)
print("Total Elements :", patients.size)
print("Data Type :", patients.dtype)
print("Memory Per Element :", patients.itemsize, "Bytes")
print("Total Memory :", patients.nbytes, "Bytes")

# Transpose the array
print("\nTranspose")
print(patients.T)

# Convert the array to float32
print("\nConvert to Float32")
print(patients.astype(np.float32))


Patient Data
[[ 98.6  72.  120. ]
 [ 99.1  76.  118. ]
 [100.2  80.  122. ]
 [ 98.4  70.  115. ]]

Dimensions : 2
Shape : (4, 3)
Total Elements : 12
Data Type : float64
Memory Per Element : 8 Bytes
Total Memory : 96 Bytes

Transpose
[[ 98.6  99.1 100.2  98.4]
 [ 72.   76.   80.   70. ]
 [120.  118.  122.  115. ]]

Convert to Float32
[[ 98.6  72.  120. ]
 [ 99.1  76.  118. ]
 [100.2  80.  122. ]
 [ 98.4  70.  115. ]]


In [ ]:
# Create a NumPy array and access elements using indexing and slicing
import numpy as np

students = np.array([
    ["Aarav", 85, 90, 88],
    ["Diya", 78, 82, 80],
    ["Kabir", 92, 95, 94],
    ["Meera", 89, 91, 90]
], dtype=object)

# Display selected elements, rows, columns, and slices
print("Student Dataset\n")
print(students)
print("\nFirst Student")
print(students[0])
print("\nLast Student")
print(students[-1])
print("\nSecond Student Name")
print(students[1, 0])
print("\nMarks Column")
print(students[:, 1])
print("\nFirst Two Students")
print(students[0:2])
print("\nName and First Two Marks")
print(students[:, 0:3])


Student Dataset

[['Aarav' 85 90 88]
 ['Diya' 78 82 80]
 ['Kabir' 92 95 94]
 ['Meera' 89 91 90]]

First Student
['Aarav' 85 90 88]

Last Student
['Meera' 89 91 90]

Second Student Name
Diya

Marks Column
[85 78 92 89]

First Two Students
[['Aarav' 85 90 88]
 ['Diya' 78 82 80]]

Name and First Two Marks
[['Aarav' 85 90]
 ['Diya' 78 82]
 ['Kabir' 92 95]
 ['Meera' 89 91]]


In [ ]:
# Create a NumPy array and select rows and columns
import numpy as np

sales = np.array([
    [101, 1200, 35],
    [102, 1800, 28],
    [103, 2400, 45],
    [104, 1500, 32]
])

# Display the array and selected data
print("Sales Dataset\n")
print(sales)
print("\nProduct IDs")
print(sales[:, 0])
print("\nPrices")
print(sales[:, 1])
print("\nUnits Sold")
print(sales[:, 2])
print("\nFirst Three Products")
print(sales[:3])
print("\nPrice and Units Columns")
print(sales[:, 1:3])


Sales Dataset

[[ 101 1200   35]
 [ 102 1800   28]
 [ 103 2400   45]
 [ 104 1500   32]]

Product IDs
[101 102 103 104]

Prices
[1200 1800 2400 1500]

Units Sold
[35 28 45 32]

First Three Products
[[ 101 1200   35]
 [ 102 1800   28]
 [ 103 2400   45]]

Price and Units Columns
[[1200   35]
 [1800   28]
 [2400   45]
 [1500   32]]


In [ ]:
# Calculate mathematical and statistical values from a NumPy array
import numpy as np

salary = np.array([42000, 48000, 51000, 45000, 60000, 55000])

# Display statistical calculations
print("Employee Salaries")
print(salary)
print("\nTotal Salary :", np.sum(salary))
print("Average Salary :", np.mean(salary))
print("Median Salary :", np.median(salary))
print("Highest Salary :", np.max(salary))
print("Lowest Salary :", np.min(salary))
print("Salary Standard Deviation :", np.std(salary))
print("Salary Variance :", np.var(salary))
print("Highest Salary Index :", np.argmax(salary))
print("Lowest Salary Index :", np.argmin(salary))


Employee Salaries
[42000 48000 51000 45000 60000 55000]

Total Salary : 301000
Average Salary : 50166.666666666664
Median Salary : 49500.0
Highest Salary : 60000
Lowest Salary : 42000
Salary Standard Deviation : 6039.223643997813
Salary Variance : 36472222.222222224
Highest Salary Index : 4
Lowest Salary Index : 0


In [ ]:
# Calculate statistical values from model accuracy scores
import numpy as np

accuracy = np.array([82.5, 84.1, 86.8, 88.2, 90.4])

# Display statistical calculations
print("Model Accuracy")
print(accuracy)
print("\nAverage Accuracy :", np.mean(accuracy))
print("Best Accuracy :", np.max(accuracy))
print("Lowest Accuracy :", np.min(accuracy))
print("Median Accuracy :", np.median(accuracy))
print("Variation :", np.std(accuracy))
print("Best Model Position :", np.argmax(accuracy))


Model Accuracy
[82.5 84.1 86.8 88.2 90.4]

Average Accuracy : 86.4
Best Accuracy : 90.4
Lowest Accuracy : 82.5
Median Accuracy : 86.8
Variation : 2.8248893783651097
Best Model Position : 4


In [ ]:
# Create the energy array and display its properties
import numpy as np

energy = np.array([420, 450, 480, 500, 530, 490, 470])

# Display the array, statistics, size, data type, and object type
print("Energy:", energy)
print("Total Energy:", np.sum(energy))
print("Average Energy:", np.mean(energy))
print("Maximum Energy:", np.max(energy))
print("Minimum Energy:", np.min(energy))
print("Number of Elements:", energy.size)
print("Data Type:", energy.dtype)
print("Object Type:", type(energy))


Energy: [420 450 480 500 530 490 470]
Total Energy: 3340
Average Energy: 477.14285714285717
Maximum Energy: 530
Minimum Energy: 420
Number of Elements: 7
Data Type: int64
Object Type: <class 'numpy.ndarray'>


In [ ]:
# Create arrays using NumPy array-generation functions
import numpy as np

print("Parking Slot Numbers")
print(np.arange(1, 21))

print("\nEmpty Parking Slots")
print(np.zeros((4, 5)))

print("\nOccupied Parking Slots")
print(np.ones((4, 5)))

print("\nParking Charges")
print(np.full((4, 5), 50))

print("\nEmpty Matrix")
print(np.empty((3, 4)))

print("\nParking IDs")
print(np.arange(100, 201, 10))

print("\nEqually Spaced Values")
print(np.linspace(0, 1, 8))

print("\nIdentity Matrix using eye()")
print(np.eye(5))

print("\nIdentity Matrix using identity()")
print(np.identity(5))


Parking Slot Numbers
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Empty Parking Slots
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

Occupied Parking Slots
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Parking Charges
[[50 50 50 50 50]
 [50 50 50 50 50]
 [50 50 50 50 50]
 [50 50 50 50 50]]

Empty Matrix
[[ 98.6  99.1 100.2  98.4]
 [ 72.   76.   80.   70. ]
 [120.  118.  122.  115. ]]

Parking IDs
[100 110 120 130 140 150 160 170 180 190 200]

Equally Spaced Values
[0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.        ]

Identity Matrix using eye()
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Identity Matrix using identity()
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# Create the farm data array and inspect its attributes
import numpy as np

farm_data = np.array([
    [28, 65, 320],
    [30, 70, 300],
    [29, 68, 310],
    [31, 72, 295],
    [27, 66, 315]
])

# Display array information
print("Farm Data")
print(farm_data)
print("\nDimensions:", farm_data.ndim)
print("Shape:", farm_data.shape)
print("Total Elements:", farm_data.size)
print("Data Type:", farm_data.dtype)
print("Memory Per Element:", farm_data.itemsize, "Bytes")
print("Total Memory:", farm_data.nbytes, "Bytes")

# Display the transpose and float32 conversion
print("\nTranspose")
print(farm_data.T)
print("\nFloat32 Array")
print(farm_data.astype(np.float32))


Farm Data
[[ 28  65 320]
 [ 30  70 300]
 [ 29  68 310]
 [ 31  72 295]
 [ 27  66 315]]

Dimensions: 2
Shape: (5, 3)
Total Elements: 15
Data Type: int64
Memory Per Element: 8 Bytes
Total Memory: 120 Bytes

Transpose
[[ 28  30  29  31  27]
 [ 65  70  68  72  66]
 [320 300 310 295 315]]

Float32 Array
[[ 28.  65. 320.]
 [ 30.  70. 300.]
 [ 29.  68. 310.]
 [ 31.  72. 295.]
 [ 27.  66. 315.]]


In [ ]:
# Create the employee dataset and access rows and columns
import numpy as np

employees = np.array([
    [101, 55000, 90],
    [102, 62000, 88],
    [103, 58000, 95],
    [104, 60000, 91],
    [105, 57000, 87]
])

# Display the requested rows, columns, and slices
print("Employee Dataset")
print(employees)
print("\nFirst Employee")
print(employees[0])
print("\nLast Employee")
print(employees[-1])
print("\nThird Employee Salary")
print(employees[2, 1])
print("\nEmployee IDs")
print(employees[:, 0])
print("\nSalaries")
print(employees[:, 1])
print("\nPerformance Scores")
print(employees[:, 2])
print("\nFirst Three Employees")
print(employees[:3])
print("\nSalary and Performance")
print(employees[:, 1:3])
print("\nLast Two Employees")
print(employees[-2:])


Employee Dataset
[[  101 55000    90]
 [  102 62000    88]
 [  103 58000    95]
 [  104 60000    91]
 [  105 57000    87]]

First Employee
[  101 55000    90]

Last Employee
[  105 57000    87]

Third Employee Salary
58000

Employee IDs
[101 102 103 104 105]

Salaries
[55000 62000 58000 60000 57000]

Performance Scores
[90 88 95 91 87]

First Three Employees
[[  101 55000    90]
 [  102 62000    88]
 [  103 58000    95]]

Salary and Performance
[[55000    90]
 [62000    88]
 [58000    95]
 [60000    91]
 [57000    87]]

Last Two Employees
[[  104 60000    91]
 [  105 57000    87]]


In [ ]:
# Calculate statistical values from the sales array
import numpy as np

sales = np.array([42000, 39000, 45000, 47000, 51000, 43000, 48000])

# Display the sales data and statistical calculations
print("Sales:", sales)
print("Total Sales:", np.sum(sales))
print("Average Sales:", np.mean(sales))
print("Median Sales:", np.median(sales))
print("Highest Sales:", np.max(sales))
print("Lowest Sales:", np.min(sales))
print("Standard Deviation:", np.std(sales))
print("Variance:", np.var(sales))
print("Highest Sales Index:", np.argmax(sales))
print("Lowest Sales Index:", np.argmin(sales))


Sales: [42000 39000 45000 47000 51000 43000 48000]
Total Sales: 315000
Average Sales: 45000.0
Median Sales: 45000.0
Highest Sales: 51000
Lowest Sales: 39000
Standard Deviation: 3741.657386773941
Variance: 14000000.0
Highest Sales Index: 4
Lowest Sales Index: 1
