---
# *Task 1 – 1D Array: Daily Water Consumption Analysis*
---

In [1]:
import numpy as np

water_consumption = [1800, 2200, 1950, 2500, 2100, 1700, 2300, 2000, 2400, 2150]

In [2]:
# 1. Convert the given water-consumption data into a NumPy array and display the complete array.

array = np.array(water_consumption)
array

array([1800, 2200, 1950, 2500, 2100, 1700, 2300, 2000, 2400, 2150])

In [3]:
# 2. Find the number of dimensions, number of elements, shape, and data type of the array.

print(array.ndim)
print(array.size)
print(array.shape)
print(array.dtype)

1
10
(10,)
int64


In [4]:
# 3. Display the water consumption recorded on the 4th day.

print(array)
print(array[3])

[1800 2200 1950 2500 2100 1700 2300 2000 2400 2150]
2500


In [5]:
# 4. Display the water consumption recorded on the last day, using indexing from the end.

print(array)
print(array[-1])

[1800 2200 1950 2500 2100 1700 2300 2000 2400 2150]
2150


In [6]:
# 5. Display the water consumption recorded from Day 3 to Day 7.

print(array)
print(array[2:7])

[1800 2200 1950 2500 2100 1700 2300 2000 2400 2150]
[1950 2500 2100 1700 2300]


In [7]:
# 6. Display the consumption recorded during the first 5 days.

print(array)
print(array[:5])

[1800 2200 1950 2500 2100 1700 2300 2000 2400 2150]
[1800 2200 1950 2500 2100]


In [8]:
# 7. Display the consumption recorded during the last 3 days.

print(array)
print(array[-3:])

[1800 2200 1950 2500 2100 1700 2300 2000 2400 2150]
[2000 2400 2150]


In [9]:
# 8. Create a NumPy array containing the day numbers from 1 to 10.

days = np.arange(1, 11)
print(days)

[ 1  2  3  4  5  6  7  8  9 10]


In [10]:
# 9. Create a NumPy array containing 5 zero values to represent days for which water consumption has not yet been recorded.

unrecorded_days = np.zeros(5)
print(unrecorded_days)

[0. 0. 0. 0. 0.]


In [11]:
# 10. Create a NumPy array containing 5 one values to represent completed daily records.

completed_daily_records = np.ones(5)
print(completed_daily_records)

[1. 1. 1. 1. 1.]


In [12]:
# 11. Create a NumPy array containing 5 values, where every value is 2000, representing the recommended daily water-consumption target.

daily_target = np.full(5, 2000)
print(daily_target)

[2000 2000 2000 2000 2000]


In [13]:
# 12. Create an empty NumPy array with 5 elements for temporary data storage.

temp_storage = np.empty(5)
print(temp_storage)

[1. 1. 1. 1. 1.]


In [14]:
# 13. Calculate the total amount of water consumed during the 10 days.

total_amount = np.sum(array)
print(total_amount)

21100


In [15]:
# 14. Calculate the average and median daily water consumption.

average = np.mean(array)
median = np.median(array)

print(average)
print(median)

2110.0
2125.0


In [16]:
# 15. Find the minimum, maximum, and variance of the daily water-consumption values.

minimum = np.min(array)
maximum = np.max(array)
variance = np.var(array)

print(minimum)
print(maximum)
print(variance)

1700
2500
58400.0


---
# *Task 2 – 2D Array: Hotel Room Occupancy Analysis*
---

In [17]:
# 1. Convert the given hotel information into a NumPy 2D array and display the complete dataset.

hotel_data = np.array([
 [101, 2, 3, 7500],
 [102, 4, 2, 9200],
 [103, 1, 5, 6800],
 [104, 3, 4, 11200],
 [105, 2, 2, 5400],
 [106, 5, 3, 13500]
])

print(hotel_data)

[[  101     2     3  7500]
 [  102     4     2  9200]
 [  103     1     5  6800]
 [  104     3     4 11200]
 [  105     2     2  5400]
 [  106     5     3 13500]]


In [18]:
# 2. Find the number of dimensions, shape, number of elements, and data type of the array

print(hotel_data.ndim)
print(hotel_data.shape)
print(hotel_data.size)
print(hotel_data.dtype)

2
(6, 4)
24
int64


In [19]:
# 3. Display the complete record of Room 103.

print(hotel_data[2])

[ 103    1    5 6800]


In [20]:
# 4. Display the number of guests staying in Room 104.

print("No of Guests:",hotel_data[3][1])

No of Guests: 3


In [21]:
# 5. Display the revenue generated by Room 105.

print("Revenue Generated by room 105:", hotel_data[4][3])

Revenue Generated by room 105: 5400


In [22]:
# 6. Display the complete record of the last room using indexing from the end.

print(hotel_data[-1])

[  106     5     3 13500]


In [23]:
# 7. Extract the Room ID column for all rooms.

print("Room IDs", hotel_data[:, 0])

Room IDs [101 102 103 104 105 106]


In [24]:
# 8. Extract the number of guests column for all rooms.

print("Guests", hotel_data[:, 1])

Guests [2 4 1 3 2 5]


In [25]:
# 9. Extract the revenue column for all rooms.

print("Revenue", hotel_data[:, 3])

Revenue [ 7500  9200  6800 11200  5400 13500]


In [26]:
# 10. Display the records of the first three rooms.

print(hotel_data[:3])

[[ 101    2    3 7500]
 [ 102    4    2 9200]
 [ 103    1    5 6800]]


In [27]:
# 11. Display the records of Room 102 to Room 105.

print(hotel_data[1:5])

[[  102     4     2  9200]
 [  103     1     5  6800]
 [  104     3     4 11200]
 [  105     2     2  5400]]


---